<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 5 Uncertainty for Individual Regression Coefficients | MATH3714 Linear Regression and Robustness</title>
  <meta name="description" content="Lecture notes for the course MATH3714 Linear Regression and Robustness at the University of Leeds, 2021/22" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 5 Uncertainty for Individual Regression Coefficients | MATH3714 Linear Regression and Robustness" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://seehuhn.github.io/MATH3714/" />
  
  <meta property="og:description" content="Lecture notes for the course MATH3714 Linear Regression and Robustness at the University of Leeds, 2021/22" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 5 Uncertainty for Individual Regression Coefficients | MATH3714 Linear Regression and Robustness" />
  
  <meta name="twitter:description" content="Lecture notes for the course MATH3714 Linear Regression and Robustness at the University of Leeds, 2021/22" />
  

<meta name="author" content="Jochen Voss" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="S04-model.html"/>
<link rel="next" href="S06-simultaneous.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P96L0SF56N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P96L0SF56N');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">MATH3714 Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html"><i class="fa fa-check"></i>About MATH3714</a>
<ul>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#notes"><i class="fa fa-check"></i>Notes and videos</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#workshops"><i class="fa fa-check"></i>Workshops and Problem Sheets</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#teams"><i class="fa fa-check"></i>Discussion Board</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#software"><i class="fa fa-check"></i>Software</a></li>
<li class="chapter" data-level="" data-path="S00-about.html"><a href="S00-about.html#assessments"><i class="fa fa-check"></i>Assessments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="S01-simple.html"><a href="S01-simple.html"><i class="fa fa-check"></i><b>1</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="S01-simple.html"><a href="S01-simple.html#residual-sum-of-squares"><i class="fa fa-check"></i><b>1.1</b> Residual Sum of Squares</a></li>
<li class="chapter" data-level="1.2" data-path="S01-simple.html"><a href="S01-simple.html#linear-regression-as-a-parameter-estimation-problem"><i class="fa fa-check"></i><b>1.2</b> Linear Regression as a Parameter Estimation Problem</a></li>
<li class="chapter" data-level="1.3" data-path="S01-simple.html"><a href="S01-simple.html#sec:simple-mat"><i class="fa fa-check"></i><b>1.3</b> Matrix Notation</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="S02-multiple.html"><a href="S02-multiple.html"><i class="fa fa-check"></i><b>2</b> Least Squares Estimates</a>
<ul>
<li class="chapter" data-level="2.1" data-path="S02-multiple.html"><a href="S02-multiple.html#data-and-models"><i class="fa fa-check"></i><b>2.1</b> Data and Models</a></li>
<li class="chapter" data-level="2.2" data-path="S02-multiple.html"><a href="S02-multiple.html#the-normal-equations"><i class="fa fa-check"></i><b>2.2</b> The Normal Equations</a></li>
<li class="chapter" data-level="2.3" data-path="S02-multiple.html"><a href="S02-multiple.html#fitted-values"><i class="fa fa-check"></i><b>2.3</b> Fitted Values</a></li>
<li class="chapter" data-level="2.4" data-path="S02-multiple.html"><a href="S02-multiple.html#example"><i class="fa fa-check"></i><b>2.4</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="I01-lm.html"><a href="I01-lm.html"><i class="fa fa-check"></i>Interlude: Linear Regression in R</a>
<ul>
<li class="chapter" data-level="" data-path="I01-lm.html"><a href="I01-lm.html#lm-fitting"><i class="fa fa-check"></i>Fitting a Model</a></li>
<li class="chapter" data-level="" data-path="I01-lm.html"><a href="I01-lm.html#lm-model"><i class="fa fa-check"></i>Understanding the Model</a></li>
<li class="chapter" data-level="" data-path="I01-lm.html"><a href="I01-lm.html#lm-predict"><i class="fa fa-check"></i>Making Predictions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="P01.html"><a href="P01.html"><i class="fa fa-check"></i>Problem Sheet 1</a></li>
<li class="chapter" data-level="3" data-path="S03-cov.html"><a href="S03-cov.html"><i class="fa fa-check"></i><b>3</b> Random Vectors and Covariance</a>
<ul>
<li class="chapter" data-level="3.1" data-path="S03-cov.html"><a href="S03-cov.html#expectation"><i class="fa fa-check"></i><b>3.1</b> Expectation</a></li>
<li class="chapter" data-level="3.2" data-path="S03-cov.html"><a href="S03-cov.html#sec:covariance"><i class="fa fa-check"></i><b>3.2</b> Covariance Matrix</a></li>
<li class="chapter" data-level="3.3" data-path="S03-cov.html"><a href="S03-cov.html#the-multivariate-normal-distribution"><i class="fa fa-check"></i><b>3.3</b> The Multivariate Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="S04-model.html"><a href="S04-model.html"><i class="fa fa-check"></i><b>4</b> Properties of the Least Squares Estimate</a>
<ul>
<li class="chapter" data-level="4.1" data-path="S04-model.html"><a href="S04-model.html#mean-and-covariance"><i class="fa fa-check"></i><b>4.1</b> Mean and Covariance</a></li>
<li class="chapter" data-level="4.2" data-path="S04-model.html"><a href="S04-model.html#hat-matrix"><i class="fa fa-check"></i><b>4.2</b> Properties of the Hat Matrix</a></li>
<li class="chapter" data-level="4.3" data-path="S04-model.html"><a href="S04-model.html#Cochran"><i class="fa fa-check"></i><b>4.3</b> Cochran’s theorem</a></li>
<li class="chapter" data-level="4.4" data-path="S04-model.html"><a href="S04-model.html#var-est-bias"><i class="fa fa-check"></i><b>4.4</b> Estimating the Error Variance</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="S05-single.html"><a href="S05-single.html"><i class="fa fa-check"></i><b>5</b> Uncertainty for Individual Regression Coefficients</a>
<ul>
<li class="chapter" data-level="5.1" data-path="S05-single.html"><a href="S05-single.html#measuring-the-estimation-error"><i class="fa fa-check"></i><b>5.1</b> Measuring the Estimation Error</a></li>
<li class="chapter" data-level="5.2" data-path="S05-single.html"><a href="S05-single.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2</b> Confidence Intervals</a></li>
<li class="chapter" data-level="5.3" data-path="S05-single.html"><a href="S05-single.html#hypthesis-tests"><i class="fa fa-check"></i><b>5.3</b> Hypthesis Tests</a></li>
<li class="chapter" data-level="5.4" data-path="S05-single.html"><a href="S05-single.html#r-experiments"><i class="fa fa-check"></i><b>5.4</b> R Experiments</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="S05-single.html"><a href="S05-single.html#fitting-the-model"><i class="fa fa-check"></i><b>5.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="5.4.2" data-path="S05-single.html"><a href="S05-single.html#estimating-the-variance-of-the-error"><i class="fa fa-check"></i><b>5.4.2</b> Estimating the Variance of the Error</a></li>
<li class="chapter" data-level="5.4.3" data-path="S05-single.html"><a href="S05-single.html#estimating-the-standard-errors"><i class="fa fa-check"></i><b>5.4.3</b> Estimating the Standard Errors</a></li>
<li class="chapter" data-level="5.4.4" data-path="S05-single.html"><a href="S05-single.html#hypothesis-tests"><i class="fa fa-check"></i><b>5.4.4</b> Hypothesis tests</a></li>
<li class="chapter" data-level="5.4.5" data-path="S05-single.html"><a href="S05-single.html#confidence-intervals-1"><i class="fa fa-check"></i><b>5.4.5</b> Confidence Intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html"><i class="fa fa-check"></i><b>6</b> Estimating Coefficients Simultaneously</a>
<ul>
<li class="chapter" data-level="6.1" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html#sec:simult-dist"><i class="fa fa-check"></i><b>6.1</b> Linear Combinations of Coefficients</a></li>
<li class="chapter" data-level="6.2" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html#sec:simult-CI"><i class="fa fa-check"></i><b>6.2</b> Confidence Regions</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html#result"><i class="fa fa-check"></i><b>6.2.1</b> Result</a></li>
<li class="chapter" data-level="6.2.2" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html#numerical-experiments"><i class="fa fa-check"></i><b>6.2.2</b> Numerical Experiments</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="S06-simultaneous.html"><a href="S06-simultaneous.html#sec:simult-test"><i class="fa fa-check"></i><b>6.3</b> Hypothesis Tests</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="I02-read.html"><a href="I02-read.html"><i class="fa fa-check"></i>Interlude: Loading Data into R</a>
<ul>
<li class="chapter" data-level="" data-path="I02-read.html"><a href="I02-read.html#importing-csv-files"><i class="fa fa-check"></i>Importing CSV Files</a></li>
<li class="chapter" data-level="" data-path="I02-read.html"><a href="I02-read.html#importing-microsoft-excel-files"><i class="fa fa-check"></i>Importing Microsoft Excel Files</a></li>
<li class="chapter" data-level="" data-path="I02-read.html"><a href="I02-read.html#checking-the-imported-data"><i class="fa fa-check"></i>Checking the Imported Data</a></li>
<li class="chapter" data-level="" data-path="I02-read.html"><a href="I02-read.html#common-problems"><i class="fa fa-check"></i>Common Problems</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="S07-examples.html"><a href="S07-examples.html"><i class="fa fa-check"></i><b>7</b> Examples</a>
<ul>
<li class="chapter" data-level="7.1" data-path="S07-examples.html"><a href="S07-examples.html#simple-confidence-interval"><i class="fa fa-check"></i><b>7.1</b> Simple Confidence Interval</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="S07-examples.html"><a href="S07-examples.html#from-first-principles"><i class="fa fa-check"></i><b>7.1.1</b> From First Principles</a></li>
<li class="chapter" data-level="7.1.2" data-path="S07-examples.html"><a href="S07-examples.html#from-the-lm-output"><i class="fa fa-check"></i><b>7.1.2</b> From the <code>lm()</code> Output</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="S07-examples.html"><a href="S07-examples.html#confidence-intervals-for-the-mean"><i class="fa fa-check"></i><b>7.2</b> Confidence Intervals for the Mean</a></li>
<li class="chapter" data-level="7.3" data-path="S07-examples.html"><a href="S07-examples.html#testing-a-single-coefficient"><i class="fa fa-check"></i><b>7.3</b> Testing a Single Coefficient</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="S07-examples.html"><a href="S07-examples.html#from-first-principles-1"><i class="fa fa-check"></i><b>7.3.1</b> From First Principles</a></li>
<li class="chapter" data-level="7.3.2" data-path="S07-examples.html"><a href="S07-examples.html#using-the-lm-output-i"><i class="fa fa-check"></i><b>7.3.2</b> Using the <code>lm()</code> Output, I</a></li>
<li class="chapter" data-level="7.3.3" data-path="S07-examples.html"><a href="S07-examples.html#using-the-lm-output-ii"><i class="fa fa-check"></i><b>7.3.3</b> Using the <code>lm()</code> Output, II</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="S07-examples.html"><a href="S07-examples.html#testing-multiple-coefficents"><i class="fa fa-check"></i><b>7.4</b> Testing Multiple Coefficents</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="S07-examples.html"><a href="S07-examples.html#from-first-principles-2"><i class="fa fa-check"></i><b>7.4.1</b> From First Principles</a></li>
<li class="chapter" data-level="7.4.2" data-path="S07-examples.html"><a href="S07-examples.html#using-the-lm-output"><i class="fa fa-check"></i><b>7.4.2</b> Using the <code>lm()</code> output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="P02.html"><a href="P02.html"><i class="fa fa-check"></i>Problem Sheet 2</a></li>
<li class="chapter" data-level="8" data-path="S08-diagnostics.html"><a href="S08-diagnostics.html"><i class="fa fa-check"></i><b>8</b> Regression Diagnostics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="S08-diagnostics.html"><a href="S08-diagnostics.html#plots"><i class="fa fa-check"></i><b>8.1</b> Diagnostic Plots</a></li>
<li class="chapter" data-level="8.2" data-path="S08-diagnostics.html"><a href="S08-diagnostics.html#R-squared"><i class="fa fa-check"></i><b>8.2</b> The Coefficient of Multiple Determination</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html"><i class="fa fa-check"></i><b>A</b> Linear Algebra Reminders</a>
<ul>
<li class="chapter" data-level="A.1" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#vectors"><i class="fa fa-check"></i><b>A.1</b> Vectors</a></li>
<li class="chapter" data-level="A.2" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#matrix-rules"><i class="fa fa-check"></i><b>A.2</b> Matrices</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#transpose"><i class="fa fa-check"></i><b>A.2.1</b> Transpose</a></li>
<li class="chapter" data-level="A.2.2" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#matrix-vector-product"><i class="fa fa-check"></i><b>A.2.2</b> Matrix-vector Product</a></li>
<li class="chapter" data-level="A.2.3" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#matrix-matrix-product"><i class="fa fa-check"></i><b>A.2.3</b> Matrix-matrix Product</a></li>
<li class="chapter" data-level="A.2.4" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#matrix-inverse"><i class="fa fa-check"></i><b>A.2.4</b> Matrix Inverse</a></li>
<li class="chapter" data-level="A.2.5" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#orthogonal-matrices"><i class="fa fa-check"></i><b>A.2.5</b> Orthogonal Matrices</a></li>
<li class="chapter" data-level="A.2.6" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#positive-definite"><i class="fa fa-check"></i><b>A.2.6</b> Positive Definite Matrices</a></li>
<li class="chapter" data-level="A.2.7" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#idempotent"><i class="fa fa-check"></i><b>A.2.7</b> Idempotent Matrices</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="Sx1-matrices.html"><a href="Sx1-matrices.html#eigenvalues"><i class="fa fa-check"></i><b>A.3</b> Eigenvalues</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="Sx2-probability.html"><a href="Sx2-probability.html"><i class="fa fa-check"></i><b>B</b> Probability Reminders</a>
<ul>
<li class="chapter" data-level="B.1" data-path="Sx2-probability.html"><a href="Sx2-probability.html#independence"><i class="fa fa-check"></i><b>B.1</b> Independence</a></li>
<li class="chapter" data-level="B.2" data-path="Sx2-probability.html"><a href="Sx2-probability.html#chi-square"><i class="fa fa-check"></i><b>B.2</b> The Chi-Squared Distribution</a></li>
<li class="chapter" data-level="B.3" data-path="Sx2-probability.html"><a href="Sx2-probability.html#t"><i class="fa fa-check"></i><b>B.3</b> The t-distribution</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MATH3714 Linear Regression and Robustness</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="S05-single" class="section level1" number="5">
<h1><span class="header-section-number">Section 5</span> Uncertainty for Individual Regression Coefficients</h1>
<p>In this section we will consider different ways to study the uncertainty in the
estimates <span class="math inline">\(\hat\beta_i\)</span> for the regression coefficient <span class="math inline">\(\beta_i\)</span>,
individually. In the following sections we will then consider the problem of
simultaneously estimating several or all coefficients.</p>
<div id="measuring-the-estimation-error" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Measuring the Estimation Error</h2>
<div class="videowrap">
<div class="videowrapper">
<iframe width="560" height="315" src="https://www.youtube.com/embed/O81XChw5mL8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
</div>
<p>We have seen that <span class="math inline">\(\hat\beta \sim \mathcal{N}(\beta, \sigma^2 C)\)</span>, where
<span class="math inline">\(C := (X^\top X)^{-1}\)</span>. Restricting this to a single coefficient, we find
<span class="math display">\[\begin{equation*}
  \hat\beta_i
  \sim \mathcal{N}\bigl( \beta_i, \sigma^2 C_{ii} \bigr),
\end{equation*}\]</span>
since the diagonal elements of the covariance matrix contains the
variances of the elements of a random vector. In practice we will not
know the value of <span class="math inline">\(\sigma^2\)</span>, so we have to estimate this from data,
using the estimator
<span class="math display">\[\begin{equation*}
  \hat\sigma^2
  = \frac{1}{n-p-1} \sum_{i=1}^n (y_i - \hat y_i)^2,
\end{equation*}\]</span>
from equation <a href="S04-model.html#eq:hat-sigma-squared">(4.5)</a>. As a first application of
Cochran’s theorem we showed in equation <a href="S04-model.html#eq:sigma-hat-chi-squared">(4.6)</a>
that
<span class="math display">\[\begin{equation*}
  \frac{1}{\sigma^2} (n - p - 1) \hat\sigma^2
  \sim \chi^2(n - p - 1).
\end{equation*}\]</span></p>
<p>Note that in the equations above, we index the rows and columns of <span class="math inline">\(C\)</span>
using <span class="math inline">\(i,j\in \{0, 1, \ldots, p\}\)</span>, <em>i.e.</em> the first row and column are
using the index 0 each. This is to match the convention for the
components of <span class="math inline">\(\beta = (\beta_0, \beta_1, \ldots, \beta_p)\)</span>.</p>
<div class="lemma">
<p><span id="lem:hat-beta-sigma-indep" class="lemma"><strong>Lemma 5.1  </strong></span>The random vector <span class="math inline">\(\hat\beta\)</span> and the random number
<span class="math inline">\(\hat\sigma^2\)</span> are independent of each other.</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-17" class="proof"><em>Proof</em>. </span>We will show that <span class="math inline">\(\hat\beta\)</span> can be written as a function of <span class="math inline">\(H\varepsilon\)</span>
and that <span class="math inline">\(\hat\sigma^2\)</span> can be written as a function of <span class="math inline">\((I-H)\varepsilon\)</span>.
The result then follows from Cochran’s theorem.</p>
<p>From lemma <a href="S04-model.html#lem:hat-beta-dist">4.1</a>
we know that the least squares estimate <span class="math inline">\(\hat\beta\)</span> can be written as
<span class="math display">\[\begin{equation*}
  \hat\beta
  = \beta + (X^\top X)^{-1} X^\top \varepsilon
\end{equation*}\]</span>
and that <span class="math inline">\(H = X (X^\top X)^{-1} X^\top\)</span>. Thus we can write <span class="math inline">\(\hat\beta\)</span> as
<span class="math display">\[\begin{align*}
  \hat\beta
  &amp;= \beta + (X^\top X)^{-1} X^\top X \, (X^\top X)^{-1} X^\top \varepsilon\\
  &amp;= \beta + (X^\top X)^{-1} X^\top H \varepsilon,
\end{align*}\]</span>
which is a function of <span class="math inline">\(H\varepsilon\)</span>.</p>
<p>Similar to the argument at the end of the previous section, we can
write <span class="math inline">\(\hat\sigma^2\)</span> as
<span class="math display">\[\begin{align*}
  (n - p - 1) \hat\sigma^2
  &amp;= (Y - \hat Y)^\top (Y - \hat Y) \\
  &amp;= (Y - H Y)^\top (Y - H Y) \\
  &amp;= Y^\top (I - H)^\top (I - H) Y \\
  &amp;= \bigl\| (I - H) Y \|.
\end{align*}\]</span>
Since <span class="math inline">\(Y = X\beta + \varepsilon\)</span> and since we know <span class="math inline">\((I-H)X = 0\)</span> from
equation <a href="S04-model.html#eq:XIH">(4.4)</a>, we find
<span class="math display">\[\begin{align*}
  \hat\sigma^2
  &amp;= \frac{1}{n-p-1} \bigl\| (I - H) (X\beta + \varepsilon) \| \\
  &amp;= \frac{1}{n-p-1} \bigl\| (I - H) \varepsilon\|,
\end{align*}\]</span>
which is a function of <span class="math inline">\((I - H)\varepsilon\)</span>.</p>
<p>From Cochran’s theorem we know that <span class="math inline">\(H \varepsilon\)</span> and <span class="math inline">\((I-H)\varepsilon\)</span> are independent
and thus we can conclude that <span class="math inline">\(\hat\beta\)</span> and <span class="math inline">\(\hat\sigma^2\)</span> are also
independent of each other. This completes the proof.</p>
</div>
<p>We now construct a quantity <span class="math inline">\(T\)</span> which measures the distance between
the estimated value <span class="math inline">\(\hat\beta_i\)</span> and the unknown true value <span class="math inline">\(\beta_i\)</span>:
<span class="math display" id="eq:single-T">\[\begin{equation}
  T
  := \frac{\hat\beta_i - \beta_i}{\sqrt{\hat\sigma^2 C_{ii}}}. \tag{5.1}
\end{equation}\]</span>
While there are many ways to measure this distance, the <span class="math inline">\(T\)</span> constructed
here has two main advantages:</p>
<ul>
<li><p>The value of <span class="math inline">\(T\)</span> can be computed from the given data, without
any reference to unknown quantities.</p></li>
<li><p>Below, we will be able to find the distribution of <span class="math inline">\(T\)</span>. This will
allow us to use <span class="math inline">\(T\)</span> to construct confidence intervals and statistical
tests.</p></li>
</ul>
<div class="lemma">
<p><span id="lem:beta-i-follows-t" class="lemma"><strong>Lemma 5.2  </strong></span>Assume that the data follows the model <a href="S04-model.html#eq:lmstats">(4.1)</a>.
Then <span class="math inline">\(T \sim t_{n-p-1}\)</span>, <em>i.e.</em> <span class="math inline">\(T\)</span> follows a
<span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-p-1\)</span> degrees of freedom (see appendix <a href="Sx2-probability.html#t">B.3</a>).</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-18" class="proof"><em>Proof</em>. </span>We have
<span class="math display">\[\begin{align*}
  T
  &amp;= \frac{(\hat\beta_i - \beta_i) / \sqrt{C_{ii}}}
      {\sqrt{\hat\sigma^2}} \\
  &amp;= \frac{(\hat\beta_i - \beta_i) / \sqrt{\sigma^2 C_{ii}}}
      {\sqrt{\hat\sigma^2 / \sigma^2}} \\
  &amp;= \frac{(\hat\beta_i - \beta_i) / \sqrt{\sigma^2 C_{ii}}}
      {\sqrt{((n - p - 1) \hat\sigma^2 / \sigma^2) / (n - p -1)}} \\
  &amp;=: \frac{Z}{\sqrt{Y / (n - p - 1)}},
\end{align*}\]</span>
where <span class="math inline">\(Z = (\hat\beta_i - \beta_i) / \sqrt{\sigma^2 C_{ii}} \sim \mathcal{N}(0,1)\)</span>
and <span class="math inline">\(Y = (n - p - 1) \hat\sigma^2/\sigma^2 \sim \chi^2(n-p-1)\)</span>
are independent, by lemma <a href="S05-single.html#lem:hat-beta-sigma-indep">5.1</a>.
Thus, <span class="math inline">\(T \sim t_{n-p-1}\)</span> as required.</p>
</div>
<p>The quantity <span class="math inline">\(\sqrt{\sigma^2 C_{ii}}\)</span> is sometimes called the
<strong>standard error</strong> of the estimator <span class="math inline">\(\hat\beta_i\)</span>, denoted by
<span class="math inline">\(\mathop{\mathrm{se}}(\hat\beta_i)\)</span>.</p>
</div>
<div id="confidence-intervals" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Confidence Intervals</h2>
<div class="videowrap">
<div class="videowrapper">
<iframe width="560" height="315" src="https://www.youtube.com/embed/aEiHk7iN5M4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
</div>
<p>Using the scaled distance <span class="math inline">\(T\)</span>, it is easy to construct a confidence
interval for <span class="math inline">\(\hat\beta_i\)</span>: For <span class="math inline">\(\alpha \in (0, 1)\)</span>, say <span class="math inline">\(\alpha = 5\%\)</span>,
lemma <a href="S05-single.html#lem:beta-i-follows-t">5.2</a> shows that
<span class="math display">\[\begin{equation*}
  P\Bigl( T \in \bigl[-t_{n-p-1}(\alpha/2), +t_{n-p-1}(\alpha/2)\bigr] \Bigr)
  = 1 - \alpha,
\end{equation*}\]</span>
where <span class="math inline">\(t_{n-p-1}(\alpha/2)\)</span> is the <span class="math inline">\((1 - \alpha/2)\)</span>-quantile of the
<span class="math inline">\(t(n-p-1)\)</span>-distribution. Rewriting this expression as a condition on
<span class="math inline">\(\hat\beta_i\)</span> instead of on <span class="math inline">\(T\)</span> gives a confidence interval for <span class="math inline">\(\beta_i\)</span>.</p>
<div class="lemma">
<p><span id="lem:single-CI" class="lemma"><strong>Lemma 5.3  </strong></span>The interval
<span class="math display">\[\begin{equation*}
  [U, V]
  := \Bigl[ \hat\beta_i - \sqrt{\hat\sigma^2 C_{ii}}t_{n-p-1}(\alpha/2), \hat\beta_i + \sqrt{\hat\sigma^2 C_{ii}}t_{n-p-1}(\alpha/2) \Bigr]
\end{equation*}\]</span>
is a <span class="math inline">\((1-\alpha)\)</span>-confidence interval for <span class="math inline">\(\beta_i\)</span>.</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-19" class="proof"><em>Proof</em>. </span>We have to show that <span class="math inline">\(P(\beta_i \in [U, V]) \geq 1-\alpha\)</span>. We have
<span class="math display">\[\begin{align*}
  &amp;\hskip-5mm \beta_i \in [U, V] \\
  &amp;\Longleftrightarrow
    \bigl| \hat\beta_i - \beta_i \bigr|
        \leq \sqrt{\hat\sigma^2 C_{ii}}t_{n-p-1}(\alpha/2) \\
  &amp;\Longleftrightarrow
    \Bigl| \frac{\hat\beta_i - \beta_i}{\sqrt{\hat\sigma^2 C_{ii}}} \Bigr|
        \leq t_{n-p-1}(\alpha/2) \\
  &amp;\Longleftrightarrow
    T \in \bigl[-t_{n-p-1}(\alpha/2), +t_{n-p-1}(\alpha/2)\bigr]
\end{align*}\]</span>
and thus <span class="math inline">\(P(\beta_i \in [U, V]) = 1 - \alpha\)</span>. This completes the proof.</p>
</div>
</div>
<div id="hypthesis-tests" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Hypthesis Tests</h2>
<div class="videowrap">
<div class="videowrapper">
<iframe width="560" height="315" src="https://www.youtube.com/embed/sAhL3_081JA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
</div>
<p>Very similar to the argument for confidence intervals, we can
derive a hypothesis test to test the hypothesis
<span class="math display">\[\begin{equation*}
  H_0\colon \beta_i = b
\end{equation*}\]</span>
against the alternative
<span class="math display">\[\begin{equation*}
  H_1\colon \beta_i \neq b.
\end{equation*}\]</span></p>
<p>Here we redefine <span class="math inline">\(T\)</span> as
<span class="math display" id="eq:single-test">\[\begin{equation}
  T
  := \frac{\hat\beta_i - b}{\sqrt{\hat\sigma^2 C_{ii}}},  \tag{5.2}
\end{equation}\]</span>
using <span class="math inline">\(b\)</span> in place of the <span class="math inline">\(\beta_i\)</span> above. When <span class="math inline">\(H_0\)</span> is true, this new
defintion of <span class="math inline">\(T\)</span> is the same as <a href="S05-single.html#eq:single-T">(5.1)</a>.</p>
<div class="lemma">
<p><span id="lem:unlabeled-div-20" class="lemma"><strong>Lemma 5.4  </strong></span>The test which rejects <span class="math inline">\(H_0\)</span> if and only if <span class="math inline">\(|T| &gt; t_{n-p-1}(\alpha/2)\)</span>
has significance level <span class="math inline">\(\alpha\)</span>.</p>
</div>
<div class="proof">
<p><span id="unlabeled-div-21" class="proof"><em>Proof</em>. </span>We have to show that the probability of type I errors (<em>i.e.</em> of wrongly
rejecting <span class="math inline">\(H_0\)</span> when it is true) is less than or equal to <span class="math inline">\(\alpha\)</span>.
Assume that <span class="math inline">\(H_0\)</span> is true. Then we have <span class="math inline">\(\beta_i = b\)</span> and thus
the <span class="math inline">\(T\)</span> defined in this section coincides with the expression from
equation <a href="S05-single.html#eq:single-T">(5.1)</a>. From lemma <a href="S05-single.html#lem:beta-i-follows-t">5.2</a>
we know that <span class="math inline">\(T \sim t(n-p-1)\)</span>. Thus we have
<span class="math display">\[\begin{align*}
  P( \mbox{type I error} )
  &amp;= P\bigl( |T| &gt; t_{n-p-1}(\alpha/2) \bigr) \\
  &amp;= P\bigl(T &lt; -t_{n-p-1}(\alpha/2) \bigr) + P\bigl(T &gt; t_{n-p-1}(\alpha/2) \bigr) \\
  &amp;= 2 P\bigl(T &gt; t_{n-p-1}(\alpha/2) \bigr) \\
  &amp;= 2 P\bigl(T &gt; t_{n-p-1}(\alpha/2) \bigr) \\
  &amp;= 2 \frac{\alpha}{2} \\
  &amp;= \alpha.
\end{align*}\]</span>
This completes the proof.</p>
</div>
<p>If we use <span class="math inline">\(b = 0\)</span> in the test, we can test whether <span class="math inline">\(\beta_i = 0\)</span>.
If <span class="math inline">\(\beta_i = 0\)</span> is true, the corresponding input <span class="math inline">\(x_i\)</span> has no influence
on the output.</p>
<p>As usual with statistical tests, one needs to be extremely careful when
performing several tests on the same data. In particular, it would be
unwise to test more than one component of <span class="math inline">\(\beta\)</span> using this procedure
for the same data. Instead, in the next section we will consider how
to perform tests for several components of <span class="math inline">\(\beta\)</span> simultaneously.
Before we do this, we will perform some experiments with R.</p>
</div>
<div id="r-experiments" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> R Experiments</h2>
<div class="videowrap">
<div class="videowrapper">
<iframe width="560" height="315" src="https://www.youtube.com/embed/CQFaMUTFvkw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>
</div>
<div id="fitting-the-model" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Fitting the model</h3>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="S05-single.html#cb43-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(stack.loss <span class="sc">~</span> ., <span class="at">data =</span> stackloss)</span>
<span id="cb43-2"><a href="S05-single.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stack.loss ~ ., data = stackloss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2377 -1.7117 -0.4551  2.3614  5.6978 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -39.9197    11.8960  -3.356  0.00375 ** 
## Air.Flow      0.7156     0.1349   5.307  5.8e-05 ***
## Water.Temp    1.2953     0.3680   3.520  0.00263 ** 
## Acid.Conc.   -0.1521     0.1563  -0.973  0.34405    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.243 on 17 degrees of freedom
## Multiple R-squared:  0.9136, Adjusted R-squared:  0.8983 
## F-statistic:  59.9 on 3 and 17 DF,  p-value: 3.016e-09</code></pre>
</div>
<div id="estimating-the-variance-of-the-error" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Estimating the Variance of the Error</h3>
<p>We can get the design matrix <span class="math inline">\(X\)</span> and the covariance matrix <span class="math inline">\(C\)</span> as follows:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="S05-single.html#cb45-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m)</span>
<span id="cb45-2"><a href="S05-single.html#cb45-2" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)</span>
<span id="cb45-3"><a href="S05-single.html#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(C, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>##             (Intercept) Air.Flow Water.Temp Acid.Conc.
## (Intercept)     13.4527   0.0273    -0.0620    -0.1594
## Air.Flow         0.0273   0.0017    -0.0035    -0.0007
## Water.Temp      -0.0620  -0.0035     0.0129     0.0000
## Acid.Conc.      -0.1594  -0.0007     0.0000     0.0023</code></pre>
<p>Next we need to estimate the variance <span class="math inline">\(\sigma^2\)</span>:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="S05-single.html#cb47-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> stackloss<span class="sc">$</span>stack.loss</span>
<span id="cb47-2"><a href="S05-single.html#cb47-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(stackloss)</span>
<span id="cb47-3"><a href="S05-single.html#cb47-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(stackloss) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb47-4"><a href="S05-single.html#cb47-4" aria-hidden="true" tabindex="-1"></a>hat.sigma2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> <span class="fu">fitted</span>(m))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n <span class="sc">-</span> p <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb47-5"><a href="S05-single.html#cb47-5" aria-hidden="true" tabindex="-1"></a>hat.sigma2</span></code></pre></div>
<pre><code>## [1] 10.51941</code></pre>
<p>The square root of this number, so the estimated standard deviation of the
<span class="math inline">\(\varepsilon_i\)</span> is shown as <code>Residual standard error</code> in the summary output above.
We check that we get the same result:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="S05-single.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(hat.sigma2)</span></code></pre></div>
<pre><code>## [1] 3.243364</code></pre>
<p>This result is also listed as the <code>Residual standard error</code> near the
bottom of the <code>summary(m)</code> output, above.</p>
</div>
<div id="estimating-the-standard-errors" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Estimating the Standard Errors</h3>
<p>We can the standard errors, <em>i.e.</em> the standard deviations
<span class="math inline">\(\mathop{\mathrm{stdev}}(\hat\beta)_i\)</span> as <span class="math inline">\(\sqrt{\hat\sigma^2 C_{ii}}\)</span>:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="S05-single.html#cb51-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(hat.sigma2 <span class="sc">*</span> <span class="fu">diag</span>(C))</span>
<span id="cb51-2"><a href="S05-single.html#cb51-2" aria-hidden="true" tabindex="-1"></a>se</span></code></pre></div>
<pre><code>## (Intercept)    Air.Flow  Water.Temp  Acid.Conc. 
##  11.8959969   0.1348582   0.3680243   0.1562940</code></pre>
<p>These values are also listed in the <code>Std. Error</code> column of the <code>summary(m)</code>
output.</p>
</div>
<div id="hypothesis-tests" class="section level3" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Hypothesis tests</h3>
<p>Let us now test the hypothesis <span class="math inline">\(H_0\colon \beta_i = 0\)</span>. The test statistic
for this case is the following:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="S05-single.html#cb53-1" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">coef</span>(m) <span class="sc">/</span> se</span>
<span id="cb53-2"><a href="S05-single.html#cb53-2" aria-hidden="true" tabindex="-1"></a>T</span></code></pre></div>
<pre><code>## (Intercept)    Air.Flow  Water.Temp  Acid.Conc. 
##  -3.3557234   5.3066130   3.5195672  -0.9733098</code></pre>
<p>These values are also listed in the <code>t value</code> column of the <code>summary(m)</code>
output.</p>
<p>Before we can perform the test, we need to choose <span class="math inline">\(\alpha\)</span> and to
find the corresponding critical value:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="S05-single.html#cb55-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb55-2"><a href="S05-single.html#cb55-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span> , n <span class="sc">-</span> p <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb55-3"><a href="S05-single.html#cb55-3" aria-hidden="true" tabindex="-1"></a>t</span></code></pre></div>
<pre><code>## [1] 2.109816</code></pre>
<p>Using the critical value <span class="math inline">\(t\)</span> we can decided whether <span class="math inline">\(H_0\)</span> should be accepted or
rejected. For example, looking at the intercept <span class="math inline">\(\beta_0\)</span>, we find <span class="math inline">\(|T_0| = |-3.3557234| &gt; 2.109816 = t_{n-p-1}(1-\alpha/2)\)</span> and thus we can reject the
hypothesis <span class="math inline">\(H_0\colon \beta_0 = 0\)</span>. This means that the intercept is
significantly different from 0.</p>
</div>
<div id="confidence-intervals-1" class="section level3" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Confidence Intervals</h3>
<p>Using the quantile <code>t</code> we can also get confidence intervals. Here we
only show the confidence interval for the intercept <span class="math inline">\(\beta_0\)</span>:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="S05-single.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">coef</span>(m)[<span class="dv">1</span>] <span class="sc">-</span> se[<span class="dv">1</span>] <span class="sc">*</span> t, <span class="fu">coef</span>(m)[<span class="dv">1</span>] <span class="sc">+</span> se[<span class="dv">1</span>] <span class="sc">*</span> t)</span></code></pre></div>
<pre><code>## (Intercept) (Intercept) 
##   -65.01803   -14.82131</code></pre>
<p>Confidence intervals for the remaining coefficients can be obtained simimlarly.</p>
<div class="mysummary">
<p><strong>Summary</strong></p>
<ul>
<li>We know how to scale the distance between individual parameter estimates
and the truth.</li>
<li>We have seen how to construct confidence intervals for <span class="math inline">\(\beta_i\)</span>.</li>
<li>We have seen how to construct statistical tests for <span class="math inline">\(\beta_i\)</span>.</li>
<li>We have understood some more of the summary output for the <code>lm()</code>
function in R.</li>
</ul>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="S04-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="S06-simultaneous.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MATH3714.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
